# Generated by Django 3.0.5 on 2020-04-16 14:24

import blog.models
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=25)),
                ('thumbnail', models.ImageField(height_field='thumbnail_width', upload_to=blog.models.UploadImage('post-images/'), width_field='thumbnail_width')),
                ('thumbnail_width', models.PositiveIntegerField()),
                ('thumbnail_height', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(unique=True)),
                ('read_time', models.PositiveIntegerField(verbose_name='Read Time Estimation')),
                ('total_view', models.PositiveIntegerField(verbose_name='Total Read')),
                ('dt_add', models.DateTimeField(auto_now_add=True, verbose_name='Date Expire')),
                ('dt_expire', models.DateTimeField(verbose_name='Date Expire')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_picked', models.BooleanField(default=False, verbose_name='Editor Pick')),
                ('heading', models.CharField(max_length=255, verbose_name='Heading')),
                ('snippet', models.TextField(verbose_name='Snippet')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content')),
                ('thumbnail', models.ImageField(height_field='thumbnail_width', upload_to=blog.models.UploadImage('post-images/'), width_field='thumbnail_width')),
                ('thumbnail_width', models.PositiveIntegerField()),
                ('thumbnail_height', models.PositiveIntegerField()),
                ('categories', models.ManyToManyField(related_name='categories', to='blog.Category', verbose_name='Other Category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PostRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_add', models.DateTimeField(auto_now_add=True, verbose_name='Date Expire')),
                ('rate', models.PositiveIntegerField(verbose_name='Total Read')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
                ('viewer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Viewer')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Writer'),
        ),
    ]
