# Generated by Django 3.0.5 on 2020-04-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dt_expire',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date Expire'),
        ),
    ]
