# Generated by Django 3.0.5 on 2020-04-17 00:56

import blog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200416_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=20, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+99999999' up to 15 digits allowed", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, height_field='thumbnail_height', upload_to=blog.models.UploadImage('post-images/'), width_field='thumbnail_width'),
        ),
        migrations.AlterField(
            model_name='category',
            name='thumbnail_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='thumbnail_width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='total_view',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Read'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='url',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
