# Generated by Django 3.0.5 on 2020-04-23 03:18

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(default='', max_length=255, verbose_name='Source'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(height_field='thumbnail_height', upload_to=blog.models.UploadImage('post-images/'), width_field='thumbnail_width'),
        ),
    ]
