# Generated by Django 3.0.5 on 2020-04-30 09:06

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200423_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, height_field='thumbnail_height', upload_to=blog.models.UploadImage('category-images/'), width_field='thumbnail_width'),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.CharField(blank=True, max_length=255, verbose_name='Source'),
        ),
    ]
